### ISSUE TITLE
Proposal: MSB based unsigned varint

### ISSUE THREAD

**Issue by jbenet** [multiformats/unsigned-varint#1]
# MSB based unsigned varint

It is based on the [varint of the Go standard library](https://golang.org/src/encoding/binary/varint.go), with some modifications:

- Dropping zig-zag encoding of signed ints. Multiformats use varints for indexing into tables. These are always positive indices.
- There is no max. The Go implementation has a "64-bit integer" max (using 10 bytes for representation). Thankfully, the Go implementation leaves the door open to grow the integer if need be. Here, we explicitly state there is no maxmimum. _There is always a continuation bit._
- Implementations of each multiformat will give recommended maxes to avoid memory attacks, and varint implementations SHOULD either:
  - specify a soft max (a max in the implementation though not in the spec)
  - or require clients (like a `mulithash` implementation) to specify the max.

## Spec

The encoding is:
- unsigned integers are serialized 7 bits at a time, starting with the
  least significant bits
- the most significant bit (msb) in each output byte indicates if there
  is a continuation byte (msb = 1)

**Comment by jbenet** [comment]
We should probably do this one, as it's much simpler, and our varints are not expected to ever get beyond 32bits. 

Group varints are more complicated and harder to implement. I'll give a week for people to voice counter opinion.

**Comment by whyrusleeping** [comment]
So its like the Uvarint in go's stdlib? I should be able to use that library interchangeably?

**Comment by Kubuxu** [comment]
To clear up:
10 bit number: `0bJIHGFEDCBA` would be encoded as: `0b1HGFEDCBA, 0b0000000JI`

**Comment by jbenet** [comment]
@whyrusleeping not sure, verify for yourself. the above protocol is the correct description.

**Comment by jbenet** [comment]
I'm annoyed that these are little-endian. Network things should always be big-endian. Wonder why protobuf made this call (go varints come from protobuf) ....

https://play.golang.org/p/EV9uyPWUKM

```
dec   hex varint  varint buf
1     0x01        [1]
127   0x7f        [127]
128   0x8001      [128 1]
200   0xc801      [200 1]
256   0x8002      [128 2]
1024  0x8008      [128 8]
16384 0x808001    [128 128 1]
```

**Comment by jbenet** [comment]
But i guess, because protobuf varints have well tested impls in tons of langs.

**Comment by jbenet** [comment]
We're going with these. I'm probably going to regret the endianness in a few years, but i rather not argue why people can't use existing protobuf implementations...
