### ISSUE TITLE
Is 0 supported? How?

### ISSUE THREAD

**Issue by jmitchell** [multiformats/unsigned-varint#10]
The encoding for 0 is unspecified.

I assume like most unsigned ints, it is supported, and that all outputs must be at least 1 byte long. Those assumptions would imply 0 encodes as '0b00000000'. Please clarify in the spec.

**Comment by Kubuxu** [comment]
> unsigned integers are serialized 7 bits at a time, starting with the least significant bits
    the most significant bit (msb) in each output byte indicates if there is a continuation byte (msb = 1)
    there are no signed integers

I think this algorithm is quite clear and can be applied to 0 too. Yes, 0 is 0 encoded.

**Comment by jmitchell** [comment]
Respectfully, I still maintain it's underspecified. Although most developers who have experience with other varints may intuit the "right" thing it wouldn't be based solely on the spec.

In conventional contexts that support unsigned 64, 32, 16, or 8 bit integers, 0 has 4 different encodings. Is there anything preventing 0 being encoded as, e.g. `0b10000000_00000000` (or other similar extensions)? This relates to the canonical form matter (see #5).

If we assume the input is an unsigned 8-bit representation of 0, we'd take the least-significant 7 bits with an unset continuation bit and get `0b00000000`. Assuming every source bit must be represented in the encoding, we'd have to prepend another byte with the continuation bit set (`0b10000000`), suggesting `0 : u8` encodes to the unsigned-varint `0b10000000_00000000`.

Aside from existing conventions favoring 64, 32, 16, and 8 bit unsigned integers, there's nothing preventing an input n-bit unsigned integer for any length n. For example, the 1-bit unsigned integer has two values `0b0` = 0 and `0b1` = 1. A priori there's nothing fundamentally preventing the concept of a 0-bit unsigned integer, which only has one inhabitant: `0b` = 0. It's unlikely anyone implementing this algorithm would actually apply it to an unsigned 0-bit int because they take no space and therefore aren't useful in any binary serialization. However, somebody could use the concept of a 0-bit unsigned integer input and conclude 0 encodes to the empty byte array. _"Least significant 7 bits? There are none, so I must be done."_

Without clarifying assumptions about the encoding of the input or the minimum length of the output there's ambiguity. Simply specifying one or the other would alleviate these concerns.

**Comment by eminence** [comment]
> If we assume the input is an unsigned 8-bit representation of 0

I think it would be more natural to assume that there is a 1-bit representation of zero, namely `0b0`.   Just like there is a 1-bit representation of one (`0b1`).  You'll note that the README shows an example where the value `1` encodes to `0b00000001` and not `0b10000001_00000000`.

So while I agree that the specification isn't explicit about this point, I would suggest that the canonical encoding should be the one with the fewest number of octets.   I expect however that a compliant decoder would be able to decode the 2-byte varint `0b10000001_00000000` into the value `1`.

**Comment by Stebalien** [comment]
0 is now defined to be a single zero byte.
