### ISSUE TITLE
Suggestion for an upfront-length, compatibly-ordered varint

### ISSUE THREAD

**Issue by wchargin** [multiformats/unsigned-varint#12]
In [this talk][1] at time 39:31, D. Richard Hipp (creator of SQLite)
describes the variable-length integer format used for SQLite’s BTrees.
The format is similar to the format currently described in this
repository, with the differences that the content is stored in
big-endian order and that the ninth byte is entirely filled with content
so that the maximum magnitude is exactly 64 bits.

[1]: https://youtu.be/gpxnbly9bz4?t=2371

He describes the result as “a mistake” and “a failure”, and advises
designers of any varint system to consider the following criteria:

 1. The first byte should determine the magnitude of the integer.
 2. The encoded ordering should be compatible with the logical ordering.

In particular, he suggests the following scheme (here, A0 through A8 are
code units to be decoded):

|      A0 | Value                                |
|--------:|:-------------------------------------|
|   0–240 | A0                                   |
| 241–248 | 240 + 256 × (A0 – 241) + A1          |
|     249 | 2288 + 256 × A1 + A2                 |
|     250 | A1…A3 as a 3-byte big-endian integer |
|     251 | A1…A4 as a 4-byte big-endian integer |
|     252 | A1…A5 as a 5-byte big-endian integer |
|     253 | A1…A6 as a 6-byte big-endian integer |
|     254 | A1…A7 as a 7-byte big-endian integer |
|     255 | A1…A8 as a 8-byte big-endian integer |

It appears that this was important enough for SQLite4 to switch its
varint format to exactly what is described above. More details,
including the decoding and encoding algorithms, appear in the [SQLite
docs][sq-docs].

[sq-docs]: https://sqlite.org/src4/doc/trunk/www/varint.wiki

The importance of property (1) is recognized by multihash; this
(according to its README) is why a multihash’s size appears at the
beginning of the hash instead of the end. Without this property, you
can’t skip over elements in a stream; you have to read every byte.

The importance of property (2) is recognized by UTF-8, which has the
analogous property: to compare two UTF-8 encoded codepoints, it suffices
to compare their raw code units. This raises the performance ceiling on
hot-loop operations by removing an encode/decode step, which in turn
enables hardware-accelerated implementations, like `repz cmpsb` on x86.

The format described above is compatible with raw unsigned 8-bit
integers of value at most 240, so preserves the soft-guarantee in the
multihash specification that “you do not need to implement varints until
the standard multihash table has more than 127 functions.”

Note that this scheme encodes unsigned integers of size up to 64 bits.
As discussed in previous issues (#9), this limitation is a good thing.

Thoughts?

(Posting this given that the README reads, “There is time to discuss the
details of this. All multiformats are far from requiring this varint.”)

**Comment by jbenet** [comment]
(1) thanks @wchargin! this is great to see-- nuggets of wisdom like that are great to surface. since `multihash` is finally getting to the IETF (thanks @msporny), we should finalize this decision ASAP.

(2) Problem with suggested structure.

We _want_ to have varints that can grow infinitely. No implementations do this, and the implementations call for establishing a soft implementation side bound. But we wanted to avoid setting some limit that would in the future be too small.

(Now of course, we dont expect function tables to need more than 8 bytes worth of entries... so for multihash's use this is not a significant thing)

(2) discussion of criteria above
> 1. The first byte should determine the magnitude of the integer.

- @wchargin mentions being able to skip the whole multihash value after reading only 1 byte (as opposed to n bytes of varint). definitely useful for us. (Though we still need to check the length of the value, so utility may be limited).

- Are there other reasons to have this property? 

> 2. The encoded ordering should be compatible with the logical ordering.

- Richard Hipp mentions this as important for being able to compare integers easily (ie `<` and `>`). Multihash's use of these varints is just for the table, where only equality matters. (i mean, it's possible to reason about hash function ranges... but unlikely to do that in a hot path).

- do we see a realistic case for multihash function code comparisons (`>` or `<`, not `=`). in a hot path?

- other reasons to have this property?

(3) There is another important reason we may want to improve the varints we use: there are other varint structures that are much better for hardware. So if we make a change, we should do the hardware improvement too. I think whatever others do may already be covered by this encoding. (cc @whyrusleeping )

(4) We've been using multihash for a few years so there's a ton of multihashes out there with this varint. BUT since only blake2 has entries above 127 (not many users out there for this), we may be able to change varint without too much disruption. I don't think we can keep the same exact byte values though, which would def break those users.

@whyrusleeping do you know of anybody other than us using blake2 multihashes?

**Comment by whyrusleeping** [comment]
@jbenet as far as I know, nobody is using blake2b hashes yet. However, people *could* be doing so via ipfs add, so its potentially problematic. One possible solution would be to define blake2 as being the current varint encoding in the new scheme. It kinda sucks, and the exact bytes might not even be valid in the new scheme, but its an option.

As for better varints, I (and @stebalien) have thought at some length about this, and we both are in agreement that having the prefix of the varint be the length of the number is a good idea. Though, we prefer not limiting the size of the varint to 8 bytes (as @jbenet mentioned).

One scheme we talked about was (something like this, probably misremembering a few things, but its similar to the sqlite scheme). For numbers 0-127, use just one byte. If the first bit is set, then the entire first byte (sans that leading bit) becomes the number of bytes the number will use. This allows for a maximum value of something like 2^1016, which is plenty big enough for most usecases. We could even define the 'maximum length' (all bits in the first integer set) to mean use the next byte for additional length, or even values above 64 for the length start implying number lengths of 2^N.
The end result of that conversation was really 'you can optimize a varint scheme for any particular purpose you want, but no varint is going to be perfect for every scenario'

**Comment by Stebalien** [comment]
My worry is less others using the hash in go-ipfs and more others using multihashes elsewhere. A quick search turns up at least one user: https://github.com/leeola/fixity/blob/fad04a9deab7b823ea6a560d056c3fb64a881c88/hash.go

We can fork the spec but that would be unfortunate.

**Comment by wchargin** [comment]
> Richard Hipp mentions this as important for being able to compare
> integers easily (ie `<` and `>`). Multihash's use of these varints is
> just for the table, where only equality matters. […] other reasons to
> have this property?

Is this repository intended to define a general-purpose unsigned varint,
or specifically an unsigned varint to be used _only_ by multiformats?

If a general-purpose varint, then property (2) definitely seems
beneficial. The fact that people will want to sort these varints seems
like sufficient justification to me.

If a multiformats-only varint, then it’s property (2) may well be
superfluous. Reasoning about hash function ranges is a plausible way to
identify (say) the family of blake2b or skein256 hashes, but this does
seem like a pretty niche operation.

> if we make a change, we should do the hardware improvement too.

This makes sense to me, though I don’t know what it entails.

> As for better varints, I (and @Stebalien) have thought at some length
> about this

Great to have your input from experience. I’ll certainly defer to you
(plural) on this issue. :-)

> For numbers 0-127, use just one byte. If the first bit is set, then
> the entire first byte (sans that leading bit) becomes the number of
> bytes the number will use

If we do change schemes, this one also makes sense to me. It has _both_
desirable properties described above, unless I’m mistaken. (Suggestion:
define the number of additional bytes as `(a[0] & 0x7f) + 1`, so that a
leading byte of `0x80` makes sense. The max value is then 2^1024 − 1,
stored in 129 bytes each with value `0xff`.)

([Toy implementations here.][gist-impl])

[gist-impl]: https://gist.github.com/wchargin/5db484f774609c916cac61b7d151f6a0

> One possible solution would be to define blake2 as being the current
> varint encoding in the new scheme. It kinda sucks, and the exact bytes
> might not even be valid in the new scheme, but its an option.

A good idea, but unfortunately I don’t think that it works in any of the
schemes proposed so far. If I’m reading the table correctly, "0xb2 0x20"
are the code units for blake2-256 (i.e., the numeric value is 6432).
A leading byte of 0xb2 implies a 1-byte varint under SQLite, or a
51-byte varint under why’s proposal (52-byte with my modification),
while we want it to be a 2-byte varint.

**Comment by wchargin** [comment]
Friendly ping—I know that some folks wanted to resolve this quickly.

@whyrusleeping @stebalien: Seems like you two have the most context
here. How do you weigh the benefits of switching to the scheme that Why
proposed against the costs of switching and potentially invalidating
some existing hashes? How would you like to proceed?

**Comment by Stebalien** [comment]
Unfortunately, I think the costs are unknown and possibly unknowable, unless we switch and see what breaks. At the very least, we'd need buy-in from @diasdavid and then we may need to reach out to the wider community (this isn't a small change).

**Comment by tarcieri** [comment]
Seems I'm a bit late to the party here, but I've just published a crate you might be interested in:

https://crates.io/crates/vint64

It improves on some tricks for encoding "vints" in the EBML/Matroska formats, and stores the number of additional bytes as trailing zeroes in the first bit.

Decoding is as simple as an unaligned load, shifting off the trailing zeroes (and marker bit), and performing some sanity checks (if you care about them having a canonical format), i.e. no loops and no complex branching full of special cases.

If the rightmost byte of the encoded form (ala little endian) is considered the most significant, they support a bytewise lexographic order.

**Comment by Stebalien** [comment]
At this point, the ship has sailed, landed, been retired, and turned into a national monument. I agree this varint encoding is hardly perfect and we should look into alternative formats for future protocols/projects, but it's just not feasible to switch at this point.
