### ISSUE TITLE
a section for implementations?

### ISSUE THREAD

**Issue by fluency03** [multiformats/unsigned-varint#14]
Why not create a section for implementations?

**Comment by pldespaigne** [comment]
Yep I could really use a JS implementation !

**Comment by pldespaigne** [comment]
[Rust implementation](https://github.com/paritytech/unsigned-varint)

**Comment by jmcph4** [comment]
It would be good to include the status of each implementation as well. I think a table with a link to the implementation's repo/website, what license it's under, it's development status (i.e. stable, beta, etc.), and language would be ideal.

**Comment by pldespaigne** [comment]
Js implementation : [github](https://github.com/chrisdickinson/varint), [npm](https://www.npmjs.com/package/varint)

**Comment by jmcph4** [comment]
Any progress on this?

**Comment by matheusmoreira** [comment]
[I've just finished a Python implementation.][uvarint.py]

[uvarint.py]: https://github.com/matheusmoreira/uvarint.py/commits/master

**Comment by pldespaigne** [comment]
ping @jbenet

**Comment by pldespaigne** [comment]
following the merge of #16 this issue can now be closed
