### ISSUE TITLE
PrefixVarint

### ISSUE THREAD

**Issue by vmx** [multiformats/unsigned-varint#15]
We use varints a lot and there's many ways to encode them.

The LEB128 encoding we currently use is certainly nice for it's simplicity. Though the PrefixVarint isn't that much more complex, but is quite a bit faster. See code an more info at https://github.com/stoklund/varint#prefixvarint

It's really similar to LEB128, though you can even skip over bytes without looking at them for large numbers (though we don't have large numbers normally).

**Comment by Stebalien** [comment]
@vmx any reason to leave this open?
