### ISSUE TITLE
Incorrect characterization of golang varints

### ISSUE THREAD

**Issue by ZenGround0** [multiformats/unsigned-varint#17]
Apologies if I'm reading this wrong but the claim "the authors chose to restrict the maximum size to 9-bytes and made the last byte's msb be part of the number" about golang's varint does not seem correct.

Check out how golang's max uint64 (1 << 64) - 1 is serialized to a varint [here](https://play.golang.org/p/IzMv2vHj-vr).  The result is a 10 byte number `ffffffffffffffffff01` because the varint authors chose *not* to include the last byte's msb as part of the number but to use it as a continuation bit.  

The multiformats text interprets the go authors' design note about reducing maximum encoding length in varint.go as being part of the implementation but I believe it is explored as an unimplemented option.  It is not implemented for the same extendability reasons the multiformats varint chooses to interpret a high bit in the 9th byte as a continuation bit.

**Comment by Stebalien** [comment]
This seems correct. The go implementation simply supports 10-byte varints where the lat byte must be exactly 0x1.

**Comment by Stebalien** [comment]
Hm. This has already been fixed.
