### ISSUE TITLE
Is this different to unsigned LEB128?

### ISSUE THREAD

**Issue by auscompgeek** [multiformats/unsigned-varint#20]
https://en.wikipedia.org/wiki/LEB128

**Comment by jmcph4** [comment]
So, from an admittedly very brief glance of the Wikipedia page, the format differs from LEB128 in that each byte's MSB has a `1` - with the only exception being the least significant byte. [LEB128 seems to be the opposite](https://en.wikipedia.org/wiki/LEB128#Unsigned_LEB128).

In other words, the most significant byte in LEB128 will have a `0` as its MSB, while only the **least** significant byte of Multiformat's unsigned variable integer format will have a `0` bit as its MSB.

Someone more knowledgeable than myself should peer review my answer though.

**Comment by tmakarios** [comment]
@jmcph4, I believe you're right when you say "In other words, the most significant byte in LEB128 will have a `0` as its MSB", but as I read the specification, this is _also_ true of these unsigned-varints.  In fact, @vmx even said "The LEB128 encoding we currently use..." in #15.

So I think the answer to @auscompgeek's question is that they're essentially the same, except that this specification prohibits encoding numbers `2^63` and larger.

**Comment by vmx** [comment]
It is unsigned LEB128 with further restrictions, as @tmakarios already mentions it's restricted in size (`2^63`) and it also needs to be the minimal representation (which LEB128 doesn't require).

**Comment by tmakarios** [comment]
Not that it really matters for the purpose of this specification, but the [DWARF standard](http://dwarfstd.org/doc/dwarf-2.0.0.pdf) (the first reference in the Wikipedia article on LEB128) does specify "Typically,  several  of  the  high  order  bytes  will  be  zero;  discard  them" and "The integer zero is a special case, consisting of a single zero byte", which implies that the minimal representation should be used.  However, their example pseudocode for decoding unsigned LEB128 numbers doesn't enforce this restriction.
