### ISSUE TITLE
Varint size max

### ISSUE THREAD

**Issue by jbenet** [multiformats/unsigned-varint#9]
Should we have the varint size max be 64bits like the go one? (for the foreseeable future).

This should address criticisms we have received about this flexibility leading to problems. 

@Kubuxu please consider and if you agree, let's just do it. I cannot recall a good reason to leave it broader. if we need more space in the future, we can always grow it then. those kinds of sizes give us probably decades, even if the multicodec table starts growing fast.

**Comment by Kubuxu** [comment]
For 64bit varint notation we need 10 bytes of prefix which really gives 70bits of usable space. So even if 64bit varint fills we will still have 6bits of space there.

Yeah, I think maxing on 10bytes - 64bit varint is right now good idea, It is more space that we will ever use (IPv4 space is 2<sup>32</sup> for comparison)

**Comment by jbenet** [comment]
Did it. see https://github.com/multiformats/unsigned-varint#practical-maximum-of-10-bytes-for-security

maybe check my numbers as they seem to disgree with yours? i based them on the go ones.... (63bits in 10 bytes, 64bits bumps to 11 bytes). You seem to be getting 70 bits in 10 bytes, which makes sense to me (`7 * 10 = 70`)... what's up with Go's then?

**Comment by Kubuxu** [comment]
See https://golang.org/src/encoding/binary/varint.go?s=1611:1652#L19 for explanation. They say that it could be fit into 9 bytes as 10th byte contains just one bit of information but decided against it for extendibility.

The `2^31` should be `2^64-1`.
I don't know where you got:
> In the Go implementation, the target is a "64-bit integer". Since the 64th bit bumps to 11 varint bytes, the authors chose to restrict the maximum size to 10-bytes and made the last byte's msb be part of the number. 


There is version of Golang's varint that is just unsigned.

**Comment by jbenet** [comment]
whoops off by juan error. (9 byte max, not 10)

**Comment by jbenet** [comment]
fixed in https://github.com/multiformats/unsigned-varint/commit/8a6574bd229d9e158dad43acbcea7763b7807362#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by vmx** [comment]
Max size is specified and described correctly, hence closing this issue.
